import { BadgeMetadata } from '../types';

export const MOCK_BADGES: BadgeMetadata[] = [
  {
    id: 'B-001',
    programName: 'Computer Systems Servicing NC II',
    badgeType: 'Master',
    description: 'Demonstrates mastery in installing and configuring computer systems, setting up computer networks and servers, and maintaining and repairing computer systems and networks.',
    issuer: 'TESDA National',
    badgeHolder: 'Juan Dela Cruz',
    criteria: 'Successful completion of National Assessment for Computer Systems Servicing NC II',
    issuanceDate: '2023-10-15',
    verificationId: 'V-CSS-2023-001',
    validity: '2028-10-15',
    alignment: 'Philippine Qualifications Framework (PQF) Level 3',
    tags: ['IT', 'Hardware', 'Networking', 'NCII'],
    standards: ['Install and Configure Computer Systems', 'Set up Computer Networks'],
    status: 'Active',
    termsOfUse: 'This badge is the property of TESDA and is issued to the holder upon meeting the required standards.',
    hierarchyLevel: 4,
  },
  {
    id: 'B-002',
    programName: 'Cloud Computing Fundamentals',
    badgeType: 'Expert',
    description: 'Awarded for completion of the full Cloud Computing training program.',
    issuer: 'TESDA Training Center - Manila',
    badgeHolder: 'Juan Dela Cruz',
    criteria: 'Completion of all modules in the Cloud Computing training program',
    issuanceDate: '2023-08-20',
    verificationId: 'V-CC-2023-045',
    validity: 'Permanent',
    alignment: 'Institutional Standard',
    tags: ['Cloud', 'AWS', 'Azure'],
    standards: ['Cloud Infrastructure', 'Serverless Basics'],
    status: 'Active',
    termsOfUse: 'Non-transferable digital credential.',
    hierarchyLevel: 2,
  },
  {
    id: 'B-003',
    programName: 'Digital Literacy',
    badgeType: 'Proficient',
    description: 'Demonstrates proficiency in basic digital literacy skills.',
    issuer: 'TESDA Training Center - Manila',
    badgeHolder: 'Juan Dela Cruz',
    criteria: 'Passed institutional assessment for Digital Literacy module',
    issuanceDate: '2023-07-10',
    verificationId: 'V-JS-2023-012',
    validity: 'Permanent',
    alignment: 'Unit of Competency',
    tags: ['JavaScript', 'Coding'],
    standards: ['Write clean JS code', 'Implement basic algorithms'],
    status: 'Active',
    termsOfUse: 'Micro-credential for specific skill set.',
    hierarchyLevel: 1,
  }
];

export const BADGE_HIERARCHY_INFO = [
  { type: 'Proficient', level: 1, description: 'Unit of Competency / Certificate of Achievement' },
  { type: 'Expert', level: 2, description: 'Completion of Program / Certificate of Training' },
  { type: 'Skilled', level: 3, description: 'Certificate of Competency' },
  { type: 'Master', level: 4, description: 'National Certificate' },
];
